data:extend(
  {
    {
      type = "int-setting",
      name = "minimal_pollution",
      setting_type = "runtime-global",
      default_value = 100,
      allowed_values = { 25, 50, 100, 200, 400 },
      order = "a",
    },
    {
      type = "int-setting",
      name = "nature_events_every",
      setting_type = "runtime-global",
      default_value = 600,
      allowed_values = { 60, 300, 600, 900, 1200, 2400, 3600 },
      order = "b",
    },
    {
      type = "bool-setting",
      name = "flood",
      setting_type = "runtime-global",
      default_value = true,
      order = "c",
    },
    {
      type = "bool-setting",
      name = "drought",
      setting_type = "runtime-global",
      default_value = true,
      order = "d",
    },
    {
      type = "bool-setting",
      name = "fire",
      setting_type = "runtime-global",
      default_value = false,
      order = "e",
    },
    {
      type = "bool-setting",
      name = "more_agressive_base_chunks",
      setting_type = "runtime-global",
      default_value = false,
      order = "fa",
    },
    {
      type = "bool-setting",
      name = "hello_Ripley",
      setting_type = "runtime-global",
      default_value = true,
      order = "fb",
    },
    {
      type = "bool-setting",
      name = "weathering_of_cliffs",
      setting_type = "runtime-global",
      default_value = true,
      order = "fc",
    },
    {
      type = "string-setting",
      name = "dynamic_daily_cycle",
      setting_type = "runtime-global",
      allowed_values = { "the_winter_is_coming", "middle_latitude", "equator" },
      default_value = "equator",
      order = "fd",
    },
    {
      type = "string-setting",
      name = "the_night_is_dark_and_full_of_terror",
      setting_type = "runtime-global",
      allowed_values = { 0, 20, 40, 60, 80, 100, 120, "dynamic" },
      default_value = 0,
      order = "fe",
    },
    {
      type = "int-setting",
      name = "chunks",
      setting_type = "runtime-global",
      default_value = 8,
      allowed_values = { 1, 2, 4, 8, 16, 32, 64 },
      order = "g",
    },
    {
      type = "int-setting",
      name = "new_trees_chance",
      setting_type = "runtime-global",
      default_value = 25,
      allowed_values = { 5, 25, 50, 75, 100 },
      order = "h",
    },
    {
      type = "int-setting",
      name = "new_trees_count",
      setting_type = "runtime-global",
      default_value = 2,
      allowed_values = { 1, 2, 4, 8, 16 },
      order = "i",
    },
    {
      type = "int-setting",
      name = "max_trees_count",
      setting_type = "runtime-global",
      default_value = 256,
      allowed_values = { 64, 128, 256, 512, 1024 },
      order = "ja",
    },
    {
      type = "string-setting",
      name = "template",
      setting_type = "runtime-global",
      allowed_values = { "random", "sparse_forest", "forest", "dense_forest" },
      default_value = "random",
      order = "jb",
    },
    {
      type = "int-setting",
      name = "trees_evolution_chance",
      setting_type = "runtime-global",
      default_value = 25,
      allowed_values = { 5, 25, 50, 75, 100 },
      order = "k",
    },
    {
      type = "int-setting",
      name = "trees_evolution_count",
      setting_type = "runtime-global",
      default_value = 2,
      allowed_values = { 1, 2, 4, 8, 16, 32 },
      order = "l",
    },
    {
      type = "int-setting",
      name = "trees_rotted_chance",
      setting_type = "runtime-global",
      default_value = 25,
      allowed_values = { 5, 25, 50, 75, 100 },
      order = "m",
    },
    {
      type = "int-setting",
      name = "trees_rotted_count",
      setting_type = "runtime-global",
      default_value = 2,
      allowed_values = { 1, 2, 4, 8, 16, 32 },
      order = "n",
    },
    {
      type = "int-setting",
      name = "trees_rotted_tiles",
      setting_type = "runtime-global",
      default_value = 2,
      allowed_values = { 1, 2, 3, 4 },
      order = "o",
    },
  })

